name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Inject Firebase config
        env:
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
        run: |
          # create temp file with firebase config
          cat > firebase-config-temp.js << 'EOF'
          const firebaseConfig = ${{ secrets.FIREBASE_CONFIG }};
          firebase.initializeApp(firebaseConfig);
          const db = firebase.firestore();
          EOF
          
          # inject into firebase-data.js at the right place
          sed -i '/const firebaseConfig = {/,/};/c\
          const firebaseConfig = '"$FIREBASE_CONFIG"';' firebase-data.js

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2